/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewRouteImport } from './routes/new'
import { Route as MapRouteImport } from './routes/map'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as PPostIdRouteImport } from './routes/p.$postId'
import { Route as MessagesConvIdRouteImport } from './routes/messages.$convId'
import { Route as GroupsSlugRouteImport } from './routes/groups.$slug'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PPostIdRoute = PPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesConvIdRoute = MessagesConvIdRouteImport.update({
  id: '/messages/$convId',
  path: '/messages/$convId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsSlugRoute = GroupsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GroupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/groups': typeof GroupsRouteWithChildren
  '/map': typeof MapRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/messages/$convId': typeof MessagesConvIdRoute
  '/p/$postId': typeof PPostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/groups': typeof GroupsRouteWithChildren
  '/map': typeof MapRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/messages/$convId': typeof MessagesConvIdRoute
  '/p/$postId': typeof PPostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/groups': typeof GroupsRouteWithChildren
  '/map': typeof MapRoute
  '/new': typeof NewRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/groups/$slug': typeof GroupsSlugRoute
  '/messages/$convId': typeof MessagesConvIdRoute
  '/p/$postId': typeof PPostIdRoute
  '/u/$username': typeof UUsernameRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/groups'
    | '/map'
    | '/new'
    | '/notifications'
    | '/profile'
    | '/groups/$slug'
    | '/messages/$convId'
    | '/p/$postId'
    | '/u/$username'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/groups'
    | '/map'
    | '/new'
    | '/notifications'
    | '/profile'
    | '/groups/$slug'
    | '/messages/$convId'
    | '/p/$postId'
    | '/u/$username'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explore'
    | '/groups'
    | '/map'
    | '/new'
    | '/notifications'
    | '/profile'
    | '/groups/$slug'
    | '/messages/$convId'
    | '/p/$postId'
    | '/u/$username'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  MapRoute: typeof MapRoute
  NewRoute: typeof NewRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  MessagesConvIdRoute: typeof MessagesConvIdRoute
  PPostIdRoute: typeof PPostIdRoute
  UUsernameRoute: typeof UUsernameRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$postId': {
      id: '/p/$postId'
      path: '/p/$postId'
      fullPath: '/p/$postId'
      preLoaderRoute: typeof PPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$convId': {
      id: '/messages/$convId'
      path: '/messages/$convId'
      fullPath: '/messages/$convId'
      preLoaderRoute: typeof MessagesConvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$slug': {
      id: '/groups/$slug'
      path: '/$slug'
      fullPath: '/groups/$slug'
      preLoaderRoute: typeof GroupsSlugRouteImport
      parentRoute: typeof GroupsRoute
    }
  }
}

interface GroupsRouteChildren {
  GroupsSlugRoute: typeof GroupsSlugRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsSlugRoute: GroupsSlugRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  GroupsRoute: GroupsRouteWithChildren,
  MapRoute: MapRoute,
  NewRoute: NewRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  MessagesConvIdRoute: MessagesConvIdRoute,
  PPostIdRoute: PPostIdRoute,
  UUsernameRoute: UUsernameRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
